kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: catalog
  labels:
    app: eshop
    service: catalog
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
        - path: /catalog-api
          backend:
            name: catalog-api
            port:
              number: 80
